-- RPT_INFORME_SUPERVISION en REPOCSEP (Hop-only: STG_ORA_CSEP_INFORMES -> RPT)
-- Idempotente: crea tabla/indices solo si no existen (ORA-00955 = name already used).

BEGIN
  EXECUTE IMMEDIATE q'[
CREATE TABLE RPT_INFORME_SUPERVISION (
  FECHA_CARGA                   DATE,
  IDACTIVIDAD                   NUMBER(18,0),
  TXMES                         VARCHAR2(100),
  TXNUMEXP                      VARCHAR2(500),
  TXCUC                         VARCHAR2(200),
  TXESTADO                      VARCHAR2(200),
  IDADMINISTRADO                VARCHAR2(100),
  TXADMINISTRADO                VARCHAR2(4000),
  IDSUBUNIDAD                   VARCHAR2(100),
  IDUF_SIG                      VARCHAR2(100),
  TXSUBUNIDAD                   VARCHAR2(4000),
  TXCOORDINACION                VARCHAR2(500),
  TXTIPSUP                      VARCHAR2(200),
  TXFUENTE                      VARCHAR2(200),
  TXOTRAFUENTE                  VARCHAR2(4000),
  TXACCION                      VARCHAR2(4000),
  FEINICIO                      VARCHAR2(50),
  FEFIN                         VARCHAR2(50),
  TXMUESTREO                    VARCHAR2(4000),
  TXNVL_CMPLJ                   VARCHAR2(500),
  TXNVL_CMPLJ_1                 VARCHAR2(500),
  TXNVL_CMPLJ_2                 VARCHAR2(500),
  TXNVL_CMPLJ_3                 VARCHAR2(500),
  TXNOMBRE_RESP_COMISION        VARCHAR2(4000),
  TXNOMBRE_RESP_MONITOREO       VARCHAR2(4000),
  TXNOMBRE_ANAL_LEGAL           VARCHAR2(4000),
  TXNOMBRE_JEFE_ACTIVIDAD       VARCHAR2(4000),
  FEINI_ELAB_INF_ACT            VARCHAR2(50),
  TXNIVELES_REVISION            VARCHAR2(4000),
  IDEJECFILE_PRY_INF_MIN        NUMBER(18,0),
  IDEJECFILE_PRY_INF_MAX        NUMBER(18,0),
  IDEJECFILE_INF_MAX            NUMBER(18,0),
  IDTIPOEJEFILE_PRY             VARCHAR2(50),
  IDGRUPO_REVISION              NUMBER(18,0),
  IDEJECFILE_DOC_PREVIO_MAX     NUMBER(18,0),
  FEPRY_REG_INICIAL             VARCHAR2(50),
  TXPRY_NIVEL                   VARCHAR2(500),
  TXPRY_ESTADO                  VARCHAR2(500),
  FEPRY_REG                     VARCHAR2(50),
  FEPRY_MOD_ESTADO_ESPERADO     VARCHAR2(50),
  FEPRY_MOD_ESTADO_REAL         VARCHAR2(50),
  TXINFORME                     VARCHAR2(4000),
  FEINFORME_ESPERADO            VARCHAR2(50),
  FEINFORME                     VARCHAR2(50),
  FEREG_INFORME                 VARCHAR2(50),
  TXRECOMENDACION               VARCHAR2(4000),
  TXSUBSECTOR_UND               VARCHAR2(500),
  TX_DOC_DERIVACION             VARCHAR2(4000),
  TX_NUM_DOC_DERIVACION         VARCHAR2(4000),
  FE_APROB_DOC_DERIVACION       VARCHAR2(50),
  FE_DERIV_DOC_DERIVACION       VARCHAR2(50),
  TXAREADESTINO_MEMO_DERIVACION VARCHAR2(4000),
  FEINI_ELAB_INF                VARCHAR2(50),
  TX_DOCUMENTO_PREVIO           VARCHAR2(4000),
  TX_NUMERO_DOCUMENTO_PREVIO    VARCHAR2(4000),
  FE_DOCUMENTO_PREVIO           VARCHAR2(50),
  FE_REGISTRO_DOCUMENTO_PREVIO  VARCHAR2(50),
  TX_OTRO_DOCUMENTO_PREVIO      VARCHAR2(4000)
)
]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_RPT_INF_IDACT ON RPT_INFORME_SUPERVISION (IDACTIVIDAD)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_RPT_INF_CUC ON RPT_INFORME_SUPERVISION (TXCUC)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_RPT_INF_NUMEXP ON RPT_INFORME_SUPERVISION (TXNUMEXP)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
